trigger:
  - master
pool:
  vmImage: Ubuntu-16.04
steps:
  -
    task: NodeTool@0
    inputs:
      versionSpec: 12.x
    displayName: 'Install Node.js'
  -
    task: YarnInstaller@3
    inputs:
      versionSpec: 1.x
      checkLatest: true
    displayName: 'Install Latest Yarn'
  -
    task: Yarn@3
    inputs:
      arguments: install
    displayName: 'yarn install'
  -
    task: Yarn@3
    inputs:
      arguments: 'vscode:prepublish'
    displayName: 'yarn vscode:prepublish'
  -
    task: Yarn@3
    inputs:
      arguments: 'vscode:package'
    displayName: 'yarn vscode:package'
  -
    task: CopyFiles@2
    inputs:
      Contents: '*.vsix,package.json'
      TargetFolder: $(Build.ArtifactStagingDirectory)
  -
    task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      publishLocation: Container
