trigger:
  - master
  - stable
  - dev

pool:
  vmImage: Ubuntu-18.04
steps:

  - task: GitVersion@5
    inputs:
      runtime: 'core'
      useConfigFile: true
      configFilePath: 'GitVersion.yml'

  - task: setjsonvalue@1
    inputs:
      filename: 'package.json'
      numberOfLevels: '1'
      keyname1: 'version'
      valueToSet: '$(GitVersion.FullSemVer)'
  -
    task: NodeTool@0
    inputs:
      versionSpec: 12.x
    displayName: 'Install Node.js'

  -
    task: YarnInstaller@3
    inputs:
      versionSpec: 1.x
      checkLatest: true
    displayName: 'Install Latest Yarn'
  -
    task: Yarn@3
    inputs:
      arguments: install
    displayName: 'yarn install'
  
  -
    task: Yarn@3
    inputs:
      arguments: 'vscode:package'
    displayName: 'yarn vscode:package '
  -
    task: CopyFiles@2
    inputs:
      Contents: '*.vsix'
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'packages'
      publishLocation: 'Container'
