name: CI
  
  
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published]
    branches: master
  
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
       
  publish:
    name: Publish
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Yarn Install  
        run: yarn install
      - name: Yarn Publish 
        run: yarn publish --pat ${{ secrets.PUBLISH_TOKEN}}
            
     
         
          

